apiVersion: v1
kind: Service
metadata:
  name: kubectl-command-tool-client
spec:
  type: ClusterIP
  selector:
    app: kubectl-command-tool-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
