name: Build and Deploy to GKE

on:
  push:
    branches:
      - release

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: kubectl-command-cluster
  GKE_ZONE: europe-west1-b
  CLIENT_IMAGE: k-command-tool-client
  SERVER_IMAGE: k-command-tool-server

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Calculate version from commit count and prepend "v"
      - name: Set version from commit count
        id: set_version
        run: echo "VERSION=v$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # -------- Build & Push SERVER ----------
      - name: Cache Docker layers for server
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-server
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build and push server image
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            --push \
            -t kemaladlig/k-command-tool-server:$VERSION ./server

      # -------- Build & Push CLIENT ----------
      - name: Cache Docker layers for client
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-client
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push client image
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            --push \
            -t kemaladlig/k-command-tool-client:$VERSION ./client

      # -------- Set Kube credentials ----------
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # -------- Deploy to GKE ---------
      - name: Deploy Client
        run: |
          sed "s|\${VERSION}|$VERSION|g" ./client/frontend-deployment.yaml | kubectl apply -f -

      - name: Deploy Server
        run: |
          sed "s|\${VERSION}|$VERSION|g" ./server/backend-deployment.yaml | kubectl apply -f -


      # -------- Rollout Status For Deployments ---------
      - name: Wait for server deployment to finish
        run: |
          kubectl rollout status deployment/k-command-tool-server
          
      - name: Wait for client deployment to finish
        run: |
          kubectl rollout status deployment/k-command-tool-client

