name: Build and Deploy to GKE

on:
  push:
    branches:
      - release  # İstersen "main" yapabilirsin

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: kubectl-command-cluster
  GKE_ZONE: europe-west1-b
  CLIENT_IMAGE: k-command-tool-client
  SERVER_IMAGE: k-command-tool-server
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-push-deploy:
    name: Build, Push, and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # -------- Build & Push SERVER ----------
      - name: Build and push server image
        run: |
          docker build -t kemaladlig/k-command-tool-server:${{ github.sha }} ./server
          docker push kemaladlig/k-command-tool-server:${{ github.sha }}

      # -------- Build & Push CLIENT ----------
      - name: Build and push client image
        run: |
          docker build -t kemaladlig/k-command-tool-client:${{ github.sha }} ./client
          docker push kemaladlig/k-command-tool-client:${{ github.sha }}

      # -------- Set Kube credentials ----------
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # -------- Deploy to GKE ---------
      - name: Deploy Client
        run: |
          kubectl apply -f ./client/frontend-deployment.yaml

      - name: Deploy Server
        run: |
          kubectl apply -f ./server/backend-deployment.yaml

      # -------- Check Deployment Status ----------
      - name: Check Client Deployment Status
        run: |
          kubectl rollout status deployment/kubectl-command-tool-client

      - name: Check Server Deployment Status
        run: |
          kubectl rollout status deployment/kubectl-command-tool-server

      # -------- Check Pods ----------
      - name: Check Pods
        run: |
          kubectl get pods
