name: CI/CD Pipeline

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}    

    # 3. Set up Google Cloud credentials
    - name: Set up GCP credentials
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # 4. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Build and push server image
    - name: Build and push server image
      run: |
        docker build -t kemaladlig/k-command-tool-server:${GITHUB_SHA} ./server
        docker push kemaladlig/k-command-tool-server:${GITHUB_SHA}

    # 6. Build and push client image
    - name: Build and push client image
      run: |
        docker build -t kemaladlig/k-command-tool-client:${GITHUB_SHA} ./client
        docker push kemaladlig/k-command-tool-client:${GITHUB_SHA}

    # 7. Apply service YAMLs
    - name: Apply service YAMLs
      run: |
        kubectl apply -f server/backend-service.yaml --validate=false
        kubectl apply -f client/frontend-service.yaml --validate=false

    # 8. Apply deployment YAMLs
    - name: Apply deployment YAMLs
      run: |
        kubectl apply -f server/backend-deployment.yaml
        kubectl apply -f client/frontend-deployment.yaml

    # 9. Apply ingress YAML (SSL setup)
    - name: Apply Ingress YAML
      run: |
        kubectl apply -f ingress.yaml
        kubectl apply -f letsencrypt-cluster-issuer.yaml